spring:
  datasource:
    url: jdbc:sqlserver://turistguide-server.database.windows.net:1433;databaseName=turistguide-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: turistadmin
    password: password123-
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Debug settings - remove in production!
logging:
  level:
    org:
      springframework:
        web: INFO
        jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    com:
      example:
        touristguide: DEBUG
