spring:
  datasource:
    url: jdbc:sqlserver://turistguide-server.database.windows.net:1433;databaseName=turistguide-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: turistadmin
    password: password123-
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        connection:
          characterEncoding: utf-8
          useUnicode: true

# Server configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Debug settings - remove in production!
logging:
  level:
    org:
      springframework:
        web: INFO
        jdbc: INFO
      hibernate:
        SQL: INFO
        type.descriptor.sql.BasicBinder: INFO
    com:
      example:
        touristguide: INFO
