name: Build og Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: maven

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: Deploy til Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: turistguide-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
