name: Build og Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: maven

      - name: Maven Build
        run: mvn clean package

      - name: Gem Bygget Jar
        uses: actions/upload-artifact@v3
        with:
          name: turistguide
          path: target/*.jar
          retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Hent Jar Fil
        uses: actions/download-artifact@v3
        with:
          name: turistguide
          path: ./

      - name: Deploy til Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: turistguide-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./*.jar
